### PR TITLE
Indicate "proposal" stage for identifiers starting with "P"

### LINKED ISSUE #24: Parse "proposal" PubIDs with a standard identifier that starts with `P`
The identifiers that start with `P` indicate they are standards at the "proposal" stage.

We need to identify that these PubIDs indicate "proposal" stage.

```
IEEE Std PC57.13.6/D3
IEEE Std PC57.130/D15
IEEE Std PC57.130/D17
IEEE Std P802.11i/D3
IEEE Std P802.11j/D1.6
IEEE Std P802.11ma/D3.0
IEEE Std P802.11p/D11.0 April 2010
IEEE Std P802.11s/D5.0 April 2010
IEEE Unapproved Draft Std P1003.1 Draft 5.1, May 2008
IEEE Unapproved Draft Std P1003.1_D3, Jun 07
IEEE Unapproved Draft Std P1003.1_D4 , Jan 2008
IEEE Unapproved Draft Std P1016/D7, Oct 2008
IEEE Unapproved Draft Std P1016/D8, Nov 2008
```

### PR DESCRIPTION
**Pull request by mico**
closes #24

### CODE REVIEW

**Review by ronaldtse — CHANGES_REQUESTED** [review]
How can I set a PubID to "proposal stage"? Can we implement proposal as a real attribute?

**Comment by mico** [comment]
> How can I set a PubID to "proposal stage"? Can we implement proposal as a real attribute?

Do we have any real IEEE Pub ID with proposal stage? I only know about "NP" stage from ISO. Or please give me any suggestion if we're going to make a new one for IEEE.

**Comment by ronaldtse** [comment]
All the "Pnnnn" ones are "proposal stage" documents.

**Review by ronaldtse — APPROVED** [review]

**Comment by ronaldtse** [comment]
Thanks @mico !

**Pull request merged**
