### PR TITLE
Parse "IEEE Unapproved P802.21/D-14-2008-Sept"

### LINKED ISSUE #107: Parse "Unapproved" references
We need to parse references like "IEEE Unapproved P802.21/D-14-2008-Sept". The Pubid should be equal to "IEEE P802.21/D14"
```ruby
> Pubid:Ieee::Identifier.parse("IEEE P802.21/D14") == Pubid:Ieee::Identifier.parse("IEEE Unapproved P802.21/D-14-2008-Sept")
=> true
```
Original https://github.com/metanorma/mn-samples-ieee/issues/5#issuecomment-1756770801

### PR DESCRIPTION
**Pull request by mico**
closes #107

### CODE REVIEW

**Review by andrew2net — CHANGES_REQUESTED** [review]
```ruby
> Pubid::Ieee::Identifier.parse("IEEE Unapproved 11073.10471/D-02-2008-02")
/Users/andrej/RubyProjects/pubid-ieee/lib/pubid/ieee/identifier/base.rb:102:in `rescue in parse': Expected one of [IEEE_WITHOUT_PREFIX, (ORGANIZATIONS SPACE)? type_status:((draft_status:DRAFT_STATUS SPACE)? ('Draft '? type:TYPE SPACE?)?) NUMBER_PREFIX NUMBER parameters:((DRAFT / PART_SUBPART_YEAR? CORRIGENDUM? DRAFT? ISO_AMENDMENT?) PUBLICATION_DATE? edition:EDITION? DUAL_PUBIDS? ADDITIONAL_PARAMETERS?), ISO_IDENTIFIER ISO_PARAMETERS, ISO_IDENTIFIER SPACE (ORGANIZATIONS SPACE)? type_status:((draft_status:DRAFT_STATUS SPACE)? ('Draft '? type:TYPE SPACE?)?) NUMBER_PREFIX NUMBER parameters:((DRAFT / PART_SUBPART_YEAR? CORRIGENDUM? DRAFT? ISO_AMENDMENT?) PUBLICATION_DATE? edition:EDITION? DUAL_PUBIDS? ADDITIONAL_PARAMETERS?), ISO_IDENTIFIER] at line 1 char 1. (Pubid::Core::Errors::ParseError)
...
```
As I said there are many "Unapproved" IDs. Please test this gem aginst all IDs in the [index](https://github.com/relaton/relaton-data-ieee/blob/main/index-v1.yaml) file.

**Comment by mico** [comment]
> ```ruby
> > Pubid::Ieee::Identifier.parse("IEEE Unapproved 11073.10471/D-02-2008-02")
> /Users/andrej/RubyProjects/pubid-ieee/lib/pubid/ieee/identifier/base.rb:102:in `rescue in parse': Expected one of [IEEE_WITHOUT_PREFIX, (ORGANIZATIONS SPACE)? type_status:((draft_status:DRAFT_STATUS SPACE)? ('Draft '? type:TYPE SPACE?)?) NUMBER_PREFIX NUMBER parameters:((DRAFT / PART_SUBPART_YEAR? CORRIGENDUM? DRAFT? ISO_AMENDMENT?) PUBLICATION_DATE? edition:EDITION? DUAL_PUBIDS? ADDITIONAL_PARAMETERS?), ISO_IDENTIFIER ISO_PARAMETERS, ISO_IDENTIFIER SPACE (ORGANIZATIONS SPACE)? type_status:((draft_status:DRAFT_STATUS SPACE)? ('Draft '? type:TYPE SPACE?)?) NUMBER_PREFIX NUMBER parameters:((DRAFT / PART_SUBPART_YEAR? CORRIGENDUM? DRAFT? ISO_AMENDMENT?) PUBLICATION_DATE? edition:EDITION? DUAL_PUBIDS? ADDITIONAL_PARAMETERS?), ISO_IDENTIFIER] at line 1 char 1. (Pubid::Core::Errors::ParseError)
> ...
> ```
> 
> As I said there are many "Unapproved" IDs. Please test this gem aginst all IDs in the [index](https://github.com/relaton/relaton-data-ieee/blob/main/index-v1.yaml) file.

@andrew2net this is another task. (was not mentioned  We are already running tests again many "Unapproved" identifiers here https://github.com/metanorma/pubid-ieee/blob/main/spec/fixtures/pubid-parsed.txt

Do you want me to make a test that will run through all identifiers in https://github.com/relaton/relaton-data-ieee/blob/main/index-v1.yaml ?
@ronaldtse does it make sense to do that?

**Comment by andrew2net** [comment]
> @andrew2net this is another task. (was not mentioned We are already running tests again many "Unapproved" identifiers here https://github.com/metanorma/pubid-ieee/blob/main/spec/fixtures/pubid-parsed.txt
> 

We need to update these tests because the dataset has been updated since then.

> Do you want me to make a test that will run through all identifiers in https://github.com/relaton/relaton-data-ieee/blob/main/index-v1.yaml ?

I agree that testing against all the IDs is outside of this PR. But this PR needs to be tested against all the Unapproved IDs in the IEEE dataset.
To be able to use pubid-ieee with relaton-ieee we need to parse all the IDs in the dataset. So let's create another PR.

**Comment by ronaldtse** [comment]
Yes, this will be necessary as we need to parse all identifiers. Adding another PR is good.

**Comment by andrew2net** [comment]
@mico I was wrong. We need to test against doc identifiers in this file
[ieee-rawbib.csv](https://github.com/metanorma/pubid-ieee/files/14827983/ieee-rawbib.csv)

The file contains `normtitle` and `sdtnumber` elements from IEEE dataset as well as filename in the dataset.
Here is parser that currently used in relaton-ieee https://github.com/relaton/relaton-ieee/blob/main/lib/relaton_ieee/rawbib_id_parser.rb

**Review by andrew2net — APPROVED** [review]

**Pull request merged**
